#!/usr/bin/env lua

local drcom = require("core")

local function help()
    print([[
Usage: drcom [-l|-r|-h]
       -l: logoff.
       -r: relogin.
       -h: show this page.
version: drcom-web.
(C) leetking <li_Tking@163.com>
]])
end

if #arg < 1 then
    if drcom.login() then
        print("Login success!")
    else
        print("Login fail!")
    end
    return 0
end

local function logoff()
end

local function relogin()
end

for i = 1, #arg do
    if "-h" == arg[i] then
        help()
        return 0
    end
    if "-l" == arg[i] then
        logoff()
        return 0
    end
    if "-r" == arg[i] then
        relogin()
        return 0
    end
end
