#!/usr/bin/env lua
-- 生成合法ip，并且保证了在此程序同时运行也不会产生相同ip，
-- 通过clock来保证初始化种子的唯一性
-- 一般情况下已经够用了
math.randomseed(os.time()+os.clock()*10000)
io.write(("ec:17:2f:%02x:%02x:%02x"):format(math.random(255), math.random(255), math.random(255)))
