#!/usr/bin/env lua

--[[
A simple downloader liking wget.
TODO implement timeout
--]]

local http = require("socket.http")
local ltn12 = require("ltn12")

local url = ""
local method = "GET"
local saveto = io.stdout
local timeout = 30          -- 30 seconds
local verbose = true

local function _M(...)
    if verbose then
        print(...)
    end
end
local function help()
    print([[
A simple downloader liking wget, implement by lua and luaSocket.
Usage: webget [OPTIONS] [url]
       -h, --help             show this page.
       -O, --save file        save as file, default output to screen (stdout).
       -T, --time seconds     set timeout.
       -q, --quiet            be quiet.
       url                    specify the url wanna be download.
(C) leetking <li_Tking@163.com>
GPL v3
]])
end

if 1 > #arg then
    help()
    os.exit(2)
end

local file = "stdout"
local i = 1
while i <= #arg do
    if "-h" == arg[i] or "--help" == arg[i] then
        help()
        os.exit(0)
    elseif "-q" == arg[i] or "--quiet" == arg[i] then
        verbose = false
    elseif "-O" == arg[i] or "--save" == arg[i] then
        if i+1 <= #arg then
            file = arg[i+1]
            saveto = io.open(file, "wb")
            i = i+1
        else
            help()
            os.exit(2)
        end
    elseif "-T" == arg[i] or "--time" == arg[i] then
        if i+1 <= #arg then
            timeout = arg[i+1]
            i = i+1
        else
            help()
            os.exit(2)
        end
    else
        url = arg[i]
        url = url:match("https?://") and url or "http://"..url
    end

    i = i+1
end

_M(("%s `%s' to `%s' ..."):format(method, url, file))
local res, code, reshd = http.request({
    url = url,
    method = method,
    headers = {
        ["User-Agent"] = "webget/0.1",
    },
    --source = ,
    sink = ltn12.sink.file(saveto)
})

local ret = 0
if res == 1 then
    ret = 0
else
    if verbose then
        io.stderr:write("Download Faile.\n")
    end
    ret = 1
end

os.exit(ret)
